# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\13293\Desktop\1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPlainTextEdit, QScrollBar, QWidget, QApplication, QMainWindow

class test(QWidget):
    def __init__(self):
        super().__init__()
        self.textEdit = QPlainTextEdit(self)
        # 1.新建一个名字叫textEdit_send_sbar的滚动条
        self.textEdit_send_sbar = QtWidgets.QScrollBar()

        # 2.给这个滚动条添加属性
        self.textEdit_send_sbar.setStyleSheet("""
             QScrollBar:vertical {
                  border-width: 0px;
                  border: none;
                  background:rgba(64, 65, 79, 0);
                  width:12px;
                  margin: 0px 0px 0px 0px;
              }
              QScrollBar::handle:vertical {
                  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                  stop: 0 #aaaaff, stop: 0.5 #aaaaff, stop:1 #aaaaff);
                  min-height: 20px;
                  max-height: 20px;
                  margin: 0 0px 0 0px;
                  border-radius: 6px;
              }
              QScrollBar::add-line:vertical {
                  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                  stop: 0 rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                  height: 0px;
                  border: none;
                  subcontrol-position: bottom;
                  subcontrol-origin: margin;
              }
              QScrollBar::sub-line:vertical {
                  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                  stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                  height: 0 px;
                  border: none;
                  subcontrol-position: top;
                  subcontrol-origin: margin;
              }
              QScrollBar::sub-page:vertical {
              background: rgba(64, 65, 79, 0);
              }

              QScrollBar::add-page:vertical {
              background: rgba(64, 65, 79, 0);
              }
              """)

        # 3.把这个textEdit_send_bar当作属性附加到textEdit控件上
        self.textEdit.setVerticalScrollBar(self.textEdit_send_sbar)
        self.setGeometry(0, 0, 600, 600)


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.test = test()
        self.setGeometry(100, 100, 1000, 1000)
        self.setCentralWidget(self.test)


if __name__ == '__main__':
    app = QApplication(sys.argv)

    main_window = Ui_MainWindow()
    main_window.show()

    sys.exit(app.exec_())